version: '3.4'

services:
  northwindstore.app:
    container_name: northwindstore.app
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:80
    - ConnectionStrings__DB=Data Source=tcp:northwindstore.db,1433; Initial Catalog=Northwind; User ID=sa; Password=DevPass_1
    ports:
    - "80"
    networks:
    - northwindstore-dev
  northwindstore.db:
    container_name: northwindstore.db
    ports:
    - "1433"
    networks:
    - northwindstore-dev

networks:
  northwindstore-dev:
    name: northwindstore-dev